### ISSUE TITLE
Workspace Can Not be Updated From VCS-driven to CLI-driven

### ISSUE THREAD

**Issue by dmitrii-didenko** [Scalr/terraform-provider-scalr#128]
Hello

Seem like there is a bug in the provider. How to reproduce:
1. Create workspace resource:
```
resource "scalr_workspace" "testing" {
    name           = "testing"
    environment_id = "some-env-id"
    working_directory = "some-working_directory"

    vcs_provider_id = "some-vcs-id"
    vcs_repo {
      identifier = "some-repo"
      branch     = "main"
    }
}
```

2. Update workspace resource:
```
resource "scalr_workspace" "testing" {
  name           = "testing"
  environment_id = "some-env-id"
}
```
Expected result: workspace is changed from VCS-driven to CLI-driven
Actual result: no changes is applied to the workspace resource

Observation: terraform log:
`2022-05-09T22:09:50.816+0300 [WARN]  Provider "provider[\"registry.scalr.io/scalr/scalr\"]" produced an unexpected new value for scalr_workspace.testing, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .vcs_provider_id: was null, but now cty.StringVal("vcs-tuf9ua7sa4pjs90")
      - .vcs_repo: block count changed from 0 to 1`

**Comment by emocharnik** [comment]
Hi, @dmitrii-didenko. The issue is fixed as a part of the [1.0.0-rc30](https://github.com/Scalr/terraform-provider-scalr/releases/tag/v1.0.0-rc30) release
