### ISSUE TITLE
Cycle when setting up scalr_environment and `scalr_provider_configuration`

### ISSUE THREAD

**Issue by dwwhitlock** [Scalr/terraform-provider-scalr#211]
Hello - I am trying to set up a module to terraform my scalr environment the block I have is as follows:

```
resource "scalr_environment" "env" {
  name = var.scalr_environment_name
  account_id = var.scalr_account_id
  cloud_cost_estimation_enabled = true
  default_provider_configurations = concat([scalr_provider_configuration.aws.id], var.additional_default_provider_configuration_ids)
}

resource "scalr_provider_configuration" "aws" {
  name                   = "aws-${var.scalr_environment_name}-${var.aws_provider_configuration.name}"
  account_id             = var.scalr_account_id
  export_shell_variables = false

#  environments           = [scalr_environment.env.id] # creates cycle

  aws {
    account_type        = "regular"
    credentials_type    = "role_delegation"
    trusted_entity_type = "aws_service"
    role_arn = var.aws_provider_configuration.role_arn
  }
}
```

I would like for my `provider_configuration` to only be shareable with an environment, but in its current state it is not possible. I would suggest using a separate resource to create the link, similar to the AWS terraform provider for IAM:

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_policy_attachment

**Comment by emocharnik** [comment]
Hi, @dwwhitlock. We're releasing a [requested resource](https://github.com/Scalr/terraform-provider-scalr/pull/205) this week (on Friday).
