### ISSUE TITLE
Error in docs form data_source Scalr Endpoint

### ISSUE THREAD

**Issue by pgale61** [Scalr/terraform-provider-scalr#26]
I have a question about scalr_endpoint. In https://github.com/Scalr/terraform-provider-scalr/blob/develop/website/docs/d/endpoint.html.markdown it says

``` 
environment_id - (Required if workspace ID is empty) ID of the environment.
```

But there is no workspace_id attribute!

**Comment by dmytrechko** [comment]
Fixed here: https://github.com/Scalr/terraform-provider-scalr/pull/28
