### ISSUE TITLE
Users not being added to teams

### ISSUE THREAD

**Issue by annymsMthd** [Scalr/terraform-provider-scalr#302]
When using the team resource with users defined the team is created but users are never added to team. Any runs after will show users getting added in plan but applies still result in teams without users.

resource "scalr_iam_team" "example" {
  name        = "dev"
  description = "Developers"
  account_id  = "acc-xxxxxxxxxx"

  users = ["user-xxxxxxxxxx", "user-yyyyyyyyyy"] <--- never added
}

**Comment by annymsMthd** [comment]
I see users are not defined in the api https://api-explorer.scalr.com/definitions/T/Team.html
but the client posts with them https://github.com/Scalr/go-scalr/blob/develop/team.go#L91

**Comment by annymsMthd** [comment]
Actually I think this is the api doc https://docs.scalr.io/reference/create_team

**Comment by rtfee** [comment]
Are you using SAML auth or local Scalr auth?

**Comment by rtfee** [comment]
Hi @annymsMthd, we are closing this as we have not heard back from you. Please let us know if you are still experiencing issues and we'll be happy to reopen.
