### ISSUE TITLE
Bug: scalr_agent_pool_token - provider produced inconsistent result after apply 

### ISSUE THREAD

**Issue by pierluca** [Scalr/terraform-provider-scalr#306]
Applying this very simple plan fails with OpenTofu 1.6.2 and the Scalr provider 1.8.0

```
data "scalr_current_account" "account" {}

resource "scalr_environment" "dev" {
  name                            = "Development"
  account_id                      = data.scalr_current_account.account.id
  cost_estimation_enabled         = true
  policy_groups                   = []
  default_provider_configurations = []
}

resource "scalr_agent_pool" "dev" {
  name           = "agent-dev"
  account_id     = data.scalr_current_account.account.id
  environment_id = scalr_environment.dev.id
}

resource "scalr_agent_pool_token" "dev" {
  agent_pool_id = scalr_agent_pool.dev.id
  description   = "Token"
}

```

It leads to the following error:

```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to scalr_agent_pool_token.dev, provider
│ "provider[\"registry.opentofu.org/scalr/scalr\"]" produced an unexpected
│ new value: Root object was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

**Comment by emocharnik** [comment]
Hi, @pierluca. Thanks for the report, the team is investigating the issue.

**Comment by emocharnik** [comment]
@pierluca, we have pinpointed the root cause: the problem arises from using the outdated attribute `environment_id`, which will soon be phased out. We are currently restructuring agent pools with the ultimate aim of making them exclusively managed at the account level. Users will then have the ability to control access to specific environments where the pool is available through its settings. This approach will enhance the reusability of agents that require restricted access. Can you try to register the agent pool without specifying the environment id?

**Comment by pierluca** [comment]
Can you clarify how the `scalr_agent_pool` can then be restricted to specific environments from Terraform ? I'm porting a ~10k RUM org from TFC on a short timeline, and the use case I'm trying to address is that of agent pools acting in different, highly isolated environments (think dev / prod).
It wouldn't be desirable for the prod agent pool to be accessible (even accidentally) from the dev environment.

**Comment by emocharnik** [comment]
@pierluca who's responsible for management of workspaces in your organization and who will have the read access to agent pools?

**Comment by pierluca** [comment]
Despite the large(ish) infrastructure, the organization is pretty small, flat and nimble.
Think: a handful of engineers dealing with SaaS development and infrastructure, mostly dealing with a subset of workspaces on a day-to-day basis, through a VCS-based workflow.
However, for business continuity reasons, most engineers have access to privileged operations.
As such, the isolation is mostly to prevent accidents / manage risks, not so much for access control.

**Comment by emocharnik** [comment]
@pierluca so every engineer will be able to update workspace settings (link/unlink agent pool inclusively)?

**Comment by pierluca** [comment]
Correct. Though in practice there's no expectation that agent pools will be altered past the initial deployment.

**Comment by emocharnik** [comment]
Hi, @pierluca. After a more detailed investigation, I can confirm that there's an issue on the API side. I'll keep you updated.

**Comment by pierluca** [comment]
Thank you. Much appreciated.

**Comment by emocharnik** [comment]
Hi, @pierluca. The fix is already in progress, the ETA is ~1-2 weeks.

**Comment by pierluca** [comment]
Hi @emocharnik , any update on this ?
The customer's working with an ugly workaround but they'd obviously like to get rid of that.
Have a great day!

**Comment by pierluca** [comment]
It's now been integrated and works. Thank you @emocharnik !
