### ISSUE TITLE
No parameter to configure workspace environment type (unmapped, production, staging, etc)

### ISSUE THREAD

**Issue by julianr-am** [Scalr/terraform-provider-scalr#341]
Hi all,
We've noticed there is currently no way of configuring a workspace's environment type through the terraform provider. The resource `scalr_workspace` doesn't have any parameter that allows us to set it. Are there any plans to include it in the future? Or is there another way of doing it we are not aware of?
Thank you in advance.

![image](https://github.com/user-attachments/assets/dd0f559b-2775-4dbe-8dc3-90cc309cacde)

**Comment by penja** [comment]
Hi @julianr-am. 

Thank you for the FR. It's already in our backlog and will be added soon.

**Comment by rtfee** [comment]
Hi @julianr-am, this was released in version 2.1.0.

The full change log is here: https://github.com/Scalr/terraform-provider-scalr/blob/master/CHANGELOG.md
