### ISSUE TITLE
is Scalr support terragrunt?

### ISSUE THREAD

**Issue by mostafa6765** [Scalr/terraform-provider-scalr#347]
I am facing an issue with Terragrunt. Scalr produces variable not found issue with terragrunt.hcl vars.

**Comment by emocharnik** [comment]
Hi, @mostafa6765. I'm Edgar from the Product team at Scalr. Currently, we do not support Terragrunt. Except for the definition of the variables, what else Terragrunt-specific do you have in the `terragrunt.hcl` file?

**Comment by mostafa6765** [comment]
@emocharnik  yes, I have a terragrunt.hcl and set some inputs. Those inputs don't bind like terraform cloud.

Thank you. terragrunt support will be good, waiting for this feature.

**Comment by mostafa6765** [comment]
# terragrunt.hcl
```bash
terraform {
  source = "../../projects//stage"
}

include {
  path = find_in_parent_folders()
}

inputs = {
  vpc_cidr_block             = "10.0.0.0/16"
  vpc_enable_dns_hostnames   = true
  vpc_enable_dns_support     = true
  vpc_name                   = "stage-vpc"
  vpc_tags                   = {
    "Environment" = "stage"
  }

  subnet_cidrs               = ["10.0.1.0/24", "10.0.2.0/24"]
  subnet_availability_zones  = ["us-west-2a", "us-west-2b"]
  subnet_map_public_ip_on_launch = true
  subnet_name_prefix         = "stage-subnet"
  subnet_tags                = {
    "Environment" = "stage"
  }
}
```

**Comment by emocharnik** [comment]
Hi, @mostafa6765. Good news: we started working on the Terragrunt integration. I'll let you know once it's added.

**Comment by emocharnik** [comment]
@mostafa6765 we've added the beta support for Terragrunt, more information you can find here: https://updates.scalr.io
